server:
  servlet:
    context-path: /system
  port: 63110
#微服务配置
spring:
  application:
    name: system-service
  cloud:
    nacos:
      server-addr: 8.222.163.95:8848
      config: # 配置文件相关信息
        namespace: dev402
        group: xuecheng-plus-project
        file-extension: yaml
        refresh-enabled: true
      username: nacos
      password: nacos

  #  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.115.204.226:3306/xc402_system?serverTimezone=UTC&userUnicode=true&useSSL=false&
#    username: root
#    password: J7629hoah



  profiles:
    active: dev # 环境名
# 日志文件配置路径
logging:
  config: classpath:log4j2-dev.xml

# swagger 文档配置
swagger:
  title: "学成在线系统管理"
  description: "系统管理接口"
  base-package: oah.project.system
  enabled: true
  version: 1.0.0
